README.md

Updating Readme with approach document

---

.babelrc
package.json
src/charts/legend/legendComponent.js
webpack.config.js
yarn.lock

Adding babel

---

.babelrc
.eslintrc.js
LICENSE.md
__mocks__/fileMock.js
__mocks__/styleMock.js
package.json
src/charts/legend/legendComponent.js
src/charts/legend/legendComponent.test.js
webpack.config.js
webpack.parts.js
yarn.lock

Adding jest and enzyme

---

src/charts/stackedArea/StackedAreaComponent.js
src/charts/stackedArea/StackedAreaComponent.test.js
src/charts/stackedArea/stackedAreaChart.js
src/charts/stackedArea/stackedAreaChart.test.js
src/helpers/testData.js

In this PR, I am adding the code for updating and unmounting the chart, along with its tests.

Adding Update and Destroy calls

---

.codeclimate.yml
.npmignore
.travis.yml

Initial setup for getting our OSS pipeline integrated

Adding NPM, travis and codeclimate configuration

---

src/charts/stackedArea/StackedAreaComponent.js

Updating some details to follow our code styleguide

Updating component to follow react conventions

---

src/charts/constants.js
src/charts/helpers/configuration.js
src/charts/helpers/validation.js
src/charts/stackedArea/StackedAreaComponent.js
src/charts/stackedArea/StackedAreaComponent.test.js
src/charts/stackedArea/stackedAreaChart.test.js
src/stories/index.js

Updated validations and configuration setter
Added proptypes
Added demo

Adding the custom event handlers for the Stacked Area Chart

---

package.json
src/charts/stackedArea/StackedAreaComponent.js
src/charts/stackedArea/stackedAreaChart.js
src/charts/tooltip/TooltipComponent.js
src/charts/tooltip/TooltipComponent.test.js
src/charts/tooltip/tooltipChart.js
src/charts/tooltip/tooltipChart.test.js
src/helpers/testData.js
src/stories/index.js
src/tasks/release.js
webpack.config.js
webpack.parts.js
yarn.lock

Plugging tooltip to stacked area chart.

Integrating tooltip on Stacked Area

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
src/charts/tooltip/TooltipComponent.test.js

Adding templates for issues and PR
Adding contributing guide based on Britechart's

Adding Contributing guide and issue and PR templates

---

src/charts/tooltip/TooltipComponent.js
src/charts/tooltip/TooltipComponent.test.js
src/stories/index.js

Refactor TooltipComponent to use renderProps
Try out this pattern and see if it improves things
Unit tests

Refactor TooltipComponent to use renderProps

---

README.md
TOPICS.md

Updated readme, moving write-up about the approach to the topics document.
We want to get ready to promote Britecharts-React, and that means we need good documentation.

Updating Readme

---

src/charts/tooltip/tooltipChart.js

Fixing a JS error with the tooltip update on Firefox
Ran tests. Not testable in our infrastructure.

Fixes tooltip bug in firefox

---

src/charts/helpers/validation.js
src/charts/stackedArea/stackedAreaChart.test.js

Retrieving empty data possible

---

src/charts/legend/LegendComponent.js
src/charts/tooltip/TooltipComponent.js

We need to keep parity between Britecharts options and Britecharts-react proptypes.
Ran tests

Updating Legend and Tooltip Proptypes

---

package.json

dont build twice when releasing

---

src/charts/line/LineComponent.js
src/charts/line/LineComponent.test.js
src/charts/line/Readme.md
src/charts/line/lineChart.fixtures.js
src/charts/line/lineChart.js
src/charts/line/lineChart.test.js
styleguide.config.js

This PR adds the line chart.
Related to: #44
Same tests as the other charts.

[WIP] Add Line chart

---

src/charts/bar/BarComponent.test.js

This PR adds the missing tests for `BarComponent`.
Related to: https://github.com/eventbrite/britecharts-react/issues/74
Same tests as the other components.

Add BarComponent tests

---

src/charts/tooltip/TooltipComponent.js
src/charts/tooltip/TooltipComponent.test.js
src/charts/tooltip/tooltipChart.js

Fix tooltip not rendering the first data item due to falsy number check

---

src/docs/styles/custom.css
src/docs/template.html
styleguide.config.js

Adds a link from the docs homepage to the github repo
Easily move from both pages

Adds simple github link in docs homepage

---

package.json
webpack.config.js
webpack.parts.js
yarn.lock

Removing a previous setup on webpack
This didn't feel right for now

Removing d3-selection from externals

---

README.md
src/docs/styles/custom.css

Adds a table with chart thumbnails to the top of the Readme file
It is said that is important in order to get more users via github discover
Manually

Adds a set of thumbnails of our charts at the top of the readme file

---

README.md
src/docs/styles/custom.css

Cleaning demo thumbnails stuff

---

README.md
src/docs/styles/custom.css

Adding badges and hiding introduction header

Adding badges and hiding introduction header

---

README.md
src/charts/bar/Bar.js
src/charts/bar/Bar.test.js
src/charts/bar/Readme.md
src/charts/donut/Donut.js
src/charts/donut/Donut.test.js
src/charts/donut/Readme.md
src/charts/index.js
src/charts/legend/Legend.js
src/charts/legend/Legend.test.js
src/charts/legend/Readme.md
src/charts/line/Line.js
src/charts/line/Line.test.js
src/charts/line/Readme.md
src/charts/stackedArea/Readme.md
src/charts/stackedArea/StackedArea.js
src/charts/stackedArea/StackedArea.test.js
src/charts/tooltip/Tooltip.js
src/charts/tooltip/Tooltip.test.js
src/docs/styles/custom.css
styleguide.config.js

Updating docs by removing duplication on sidebar
Renaming charts to be only the chart name
Tweaking some docs styling
General cleanup

Updating docs and renaming charts by removing 'component' from the name

---

README.md
package.json
webpack.config.js
webpack.parts.js
yarn.lock

We want to provide the stylesheets that come from Britecharts as a distributable for britecharts-react
Right now users would need to access the britecharts styles in order to properly show the charts.
Fixes https://github.com/eventbrite/britecharts-react/issues/46

Copy Britecharts styles into the dist folder

---

README.md

Adds a link to the test project 
Wraps up https://github.com/eventbrite/britecharts-react/issues/80

Updating readme with test project

---

src/docs/template.html

Adding google analytics tracking to the BCR docs
Improving our dev experience
Fixes https://github.com/eventbrite/britecharts-react/issues/101

Adding google analytics tracking

---

README.md
src/charts/donut/Readme.md

Updating donut demo, Readme with typo and CDN links

Fix docs update

---

README.md
src/charts/groupedBar/GroupedBar.js
src/charts/groupedBar/GroupedBar.test.js
src/charts/groupedBar/Readme.md
src/charts/groupedBar/groupedBarChart.fixtures.js
src/charts/groupedBar/groupedBarChart.js
src/charts/groupedBar/groupedBarChart.test.js
webpack.config.js

Adds a new React wrapper for the Grouped Bar Chart component
A new GroupedBar component has been added to the components, following the style and test coverage of existing components
Takes a step towards 1:1 feature parity with Britecharts and Britecharts-React
Per the Contributing Guide, testing was performed by adding test coverage modified from the StackedArea test coverage step-by-step, then checked with the documentation for proper rendering.

[Feat] Grouped Bar Charts

---

README.md
src/charts/index.js
src/charts/stackedBar/Readme.md
src/charts/stackedBar/StackedBar.js
src/charts/stackedBar/StackedBar.test.js
src/charts/stackedBar/stackedBarChart.fixtures.js
src/charts/stackedBar/stackedBarChart.js
src/charts/stackedBar/stackedBarChart.test.js
webpack.config.js

Creates a StackedBar component
Creates a StackedBar React wrapper for the britecharts component. Development followed TDD and suggested workflow in the Contributing Guide.
Takes a step closer to 1:1 parity between Britecharts and Britecharts-React
Per the Contributing Guide, I tested by adding modified tests from the StackedArea component one by one, and adding functionality to make each test pass. Full test suite passes.

[Feature] Stacked Bar Chart

---

CONTRIBUTING.md
package.json
plopfile.js
src/charts/template/Checklist.md
src/charts/template/Component.js
src/charts/template/Component.test.js
src/charts/template/Readme.md
src/charts/template/componentChart.fixtures.js
src/charts/template/componentChart.js
src/charts/template/componentChart.test.js
yarn.lock

Integrates Plop and a set of boilerplate templates (contained in src/charts/template) to automate the process of creating a new component. Usage: yarn run plop --> enter your component name when prompted --> follow the included Checklist.md to finish.
This provides a quick way to create a new component which exists in Britecharts already. Running the command to create a new component in src/charts/xyzComponent, provides the proper file structure and naming, includes a checklist of steps to take to complete the component, and provides the necessary changes to CONTRIBUTING.md to describe the process. Though there are only a handful of components left to port, this will make it extremely easy to port future charts which are added to the main Britecharts repo.
Resolves issue: …

[Feature] Auto-generated component boilerplate with Plop

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adding refactors and updating templates

Updating issue and PR templates

---

plopfile.js
src/charts/index.js
src/charts/step/Readme.md
src/charts/step/Step.js
src/charts/step/Step.test.js
src/charts/step/stepChart.fixtures.js
src/charts/step/stepChart.js
src/charts/step/stepChart.test.js
src/charts/template/Checklist.md
src/docs/styles/custom.css
styleguide.config.js
webpack.config.js

Adds Step chart component.
Creates a new Step component, using the Plop workflow. Using Plop workflow highlighted a bug preventing the documentation from rendering correctly, so that bug is also fixed (it required ignoring src/charts/template in the styleguide.config.js file)
Moves closer to 1:1 parity between Britecharts and Britecharts-React
Per the Contributing guide, tests were implemented through modifying the Plop boilerplate, and double-checked by confirming visual accuracy in the documentation. Full test suite passes.

[Feat] Step charts and Plop fixes

---

src/charts/donut/Donut.js
src/charts/stackedBar/StackedBar.js

Fixes proptypes property naming on Donut chart

Fixing proptypes naming on Donut chart

---

webpack.config.js

Fixes the main bundle format to be UMD, the same way we are doing it for Britecharts.
This allows loading the file as a script tag that adds the contents to the global state and it doesn't change the way we load it.
Tested on the test project and core

Changing bundle from commonjs into umd

---

package.json

Improve discoverability and giving credit to the team

Updates authors and tags in package.json

---

src/charts/donut/Readme.md
src/charts/helpers/responsiveContainer.js
src/charts/legend/Legend.js

Adds the integration of donut and legend
Adds a responsive container in renderprops way
Adds an example of integration

Adds donut + legend demo

---

src/docs/template.html

Fixes paths of icons, manifest.json and more on the docs homepage
Favicons weren't being loaded on the docs homepage, only on the local version.
Checked by building the docs

Updating paths to work on github pages

---

README.md

* Working twitter link (with number of followers showing)
* The charts image alignment in the header of the page is fixed

Added correct twitter link and fixed alignment of imgs

---

package.json
src/charts/tooltip/tooltipChart.test.js
yarn.lock

Updating Britecharts version 
Fixes test due to a breaking change in Britecharts (oops!)
get the updated loading states and scatter plot
Ran and fixed tests

Updating Britecharts version and fixing tests

---

README.md
src/charts/stackedArea/stackedAreaChart.js
src/charts/step/stepChart.js

Chooses the appropriate loading states for the stacked area and step charts
Update the readme with latest additions to Britecharts
Proper loading states
Checked manually

Updates loading states

---

.travis.yml

The JIRA ticket filed by Ben explains everything. New variables with new tokens from OPS.

Added variables that reference new config tokens

---

package.json
yarn.lock

Update **Britecharts** dependency version to include latest changes.
Add bug fixes and new features specially issue #75.
For the testing process I created a clean local project using `create-react-app` and `npm linked` the local version of **Britecharts React** with the new version of **Britecharts** installed.
All demos and unit tests are running and passing.

Update Britecharts dependency version

---

src/charts/line/Readme.md

Updating Demos to use ResponsiveContainer and Responsive HOC
Show responsive utilities
Ran tests, checked manually

Using responsive container with first line demo

---

src/charts/line/Readme.md

Fixes Travis build due to case discrepancies

Updating container name

---

.eslintrc.js
.travis.yml
src/charts/helpers/colors.js
src/charts/helpers/optimizedResize.js
src/charts/legend/legendChart.test.js
yarn.lock

Updates to use Node 12
Includes eslint fixes an configuration updates 
Updating our library
Ran tests and tasks

Updating Node version to 12.2

---

.eslintrc.js
.travis.yml
Dockerfile
Makefile
package.json

Adding Docker and changing github keys
Making it easy to develop

Adding Docker and changing github keys

---

.github/FUNDING.yml

Adds funding configuration for sponsorship
Make funding more accessible

Adds Funding configuration

---

.eslintrc.js
package.json
src/typings/charts/Bar.d.ts
src/typings/charts/Bullet.d.ts
src/typings/charts/Donut.d.ts
src/typings/charts/GroupedBar.d.ts
src/typings/charts/Legend.d.ts
src/typings/charts/Line.d.ts
src/typings/charts/Sparkline.d.ts
src/typings/charts/StackedArea.d.ts
src/typings/charts/StackedBar.d.ts
src/typings/charts/Step.d.ts
src/typings/charts/Tooltip.d.ts
src/typings/charts/index.d.ts
src/typings/index.d.ts
yarn.lock

Add minimal type definitions for charts. Many properties has been left poorly typed (some `Function`, `any`, etc).
The following components has been typed:
- Bar
- Bullet
- Donut
- GroupedBar
- Legend
- Line
- Sparkline
- StackedArea
- StackedBar
- Step
- Tooltip
Helpers, loading and template, as well as  some other files remain without definitions.
**Important note**: JS Docs has been copied from proptypes. FTM, I couldn't find the way to tell styleguidist to build the docs from there, so, if we remove them from JS, we can't add the description for the props to the docs. If we remove them from the index.d.ts, intellisense won't show its related information.
Also, some `data` proptypes seems to be wrong (typed as object instead of array of objects). This could open a new issue.
The lack …

feat: adds minimal definition types for charts

---

package.json
src/charts/bullet/Readme.md
src/charts/bullet/bulletChart.fixtures.js
yarn.lock

Fixes issues in bullet chart
Bug fixes
On styleguide

Fix: Fixes bullet issues via Britecharts updates and extends demo

---

src/charts/constants.js

fix: customClick method is not working #201
